---
title: "Problem_Set_02 'Microbial Engines'"
author: "Julia Pierce (24366429)"
date: "2/7/2018"
output: html_document
---
## Problem_Set_02 "Microbial Engines"

**Learning objectives:** Discuss the role of microbial diversity and formation of coupled metabolism in driving global biogeochemical cycles.


**What are the primary geophysical and biogeochemical processes that create and sustain conditions for life on Earth? How do abiotic versus biotic processes vary with respect to matter and energy transformation and how are they interconnected? ** 
Tectonic movement along with photochemical reactions in the atmosphere allow for mixing and partitioning of chemical substrates on Earth. This cycling of nutrients allows a steady supply of substrates (food to sustain life) and the removal of products (which can be toxic, and which continue on through their chemical cycle to again become substrates).

Abiotic processes tend to rely on acid/base reactions, meaning the transfer of protons. Biotic processes rely on redox reactions, which occur using a series of electron and proton transfers from a limited set of substrates. Abiotic and biotic cycles feed into eachother, each cycle using the products as inputs/substrate into their own cycles. This interconnectedness helps maintain these cycles, and prevets substrates on Earth from being transformed completely to end products and depleting substrates required for life.

**Why is Earth’s redox state considered an emergent property?**  
The Earth’s redox state is considered an emergent property because it depends on both geochemical processes and microbial metabolic processes. Depending on geochemical processes, there will be different nutrient niches, which will contain different populations of microbes. As these microbes perform their various metabolic processes, different byproducts will be returned to the environment. Thus, as geochemical cycles and microbial metabolic processes shift and change in an area, the redox state of the Earth also sifts.
 
**How do reversible electron transfer reactions give rise to element and nutrient cycles at different ecological scales? What strategies do microbes use to overcome thermodynamic barriers to reversible electron flow? ** 
Reversible electron transfer reactions give rise to element and nutrient cycles based on different environmental conditions that allow both the forward and reverse reaction to be thermodynamically favorable. As both forward and reverse reaction are favorable under different environmental conditions (substrate availability, products, etc.), a stable nutrient cycle arises. These cycles can be carried out by multiple micoorganisms that are spatially separated, like the nitrogen cycle. Others, like methane formation and oxidation can be carried out by closely related microbes. When it is necessary to overcome thermodynamic barriers, energy (adenosine 5 ́-triphosphate) can be expended (such as in carbon fixation) to do the reverse of energy producing (acetate oxidation to carbon dioxide) reactions.

**Using information provided in the text, describe how the nitrogen cycle partitions between different redox “niches” and microbial groups. Is there a relationship between the nitrogen cycle and climate change?**  
The different stages of the nitrogen cycle all require different amounts of oxygen, corresponding to different redox niches, and the other microbes that will be in that environment. In nitrogen fixation, nitrogen gas is fixed from our atmosphere into ammonium. This is done by nitrogenase, which is inhibited by oxygen, yet this is still done in many microbes in aerobic environments. Nitrification, the oxidation of ammonium to nitrite and finally nitrate, happens in aerobic environments. Denitrification, the anaerobic oxidation of nitrate and nitrite to nitrogen gas, occurs in anoxic/anaerobic environments.
Indirectly, the nitrogen cycle is connected to climate change. All microbes require nitrogen to synthesize protein and nucleic acids, and the only method of nitrogen fixation is via microorganisms. The nitrogen cycle is what controls the amount of available fixed nitrogen, which in turn affects the number of microbes carrying out various other reactions, which in turn produces the Earth’s atmosphere. Additionally, if something were to shift in the nitrogen cycle and affect those microbes involved, it would in turn affect the overall microbial community. The nitrogen cycle does not directly affect climate change, as only nitrogen and hydrogen gas are emitted during nitrogen fixation, nitrification, or denitrification, neither of which are greenhouse gases.

**What is the relationship between microbial diversity and metabolic diversity and how does this relate to the discovery of new protein families from microbial community genomes?**  
Even though microorganisms are exteremely diverse, there still exists a constant set of core genes
that control the predominant redox reactions that play an integral role in life and biogeochemical cycles. So, while microbes themselves are diverse they share many common proteins (etc.) in their metabolism.

Theoretically, there can be limitless evolutionary diversity in nature. We are still discovering unique protein families, in proportion to sampling efforts. As more genomes are sequenced, more protein families are discovered.

**On what basis do the authors consider microbes the guardians of metabolism?**
Horizontal and vertical gene transfer have allowed metabolic pathways to be widespread amoung microbes. Thus, even if an environmental change makes the given metabolic pathway unfavorable, there are other surviving microorganisms containing the genes for the metabolic pathway. The given metabolic pathway may not even be used by the surviving microbe, but given environmental pressures the pathway may again be thermodynamically favorable, and the microorganism can again express the metabolic pathway.
