---
title: "Problem Set 1 Prokaryotes: The unseen majority"
author: "Julia Pierce (24366429)"
date: "2/7/2018"
output: html_document
---

##Problem Set 1 Prokaryotes: The unseen majority
**Learning objectives:**  
Describe the numerical abundance of microbial life in relation to the ecology and biogeochemistry of Earth systems.


**What are the primary prokaryotic habitats on Earth and how do they vary with respect to their capacity to support life? Provide a breakdown of total cell abundance for each primary habitat from the tables provided in the text.**    
Aquatic habitats - contains fewest number of cells, 12 x 10^28^  
Soil- contains the third highest number of cells, 26 x 10^28^   
Marine subsurface- contains the highest numbers of cells, 355 x 10^28^  
Terrestrial subsurface- ontains the second highest number of cells, 25-250 x 10^28^

Each of these environmental compartments contain varying amounts of carbon and other nutrients, affecting their capacity to support life

**What is the estimated prokaryotic cell abundance in the upper 200 m of the ocean and what fraction of this biomass is represented by marine cyanobacterium including Prochlorococcus? What is the significance of this ratio with respect to carbon cycling in the ocean and the atmospheric composition of the Earth?**  
There are 3.6 x 10^28^ cells in the upper 200m of the ocean, at a density of 5 x 10^5^ cells/mL. Autotrophic cyanobacteria, including Prochlorococcus, have a density of 4 x 10^4^ cells/mL.

(4 x 10^4^ autotrophs/mL)/(5 x 10^5^ total cells/mL) = 0.08 = 8% of cells are autotrophic cyanobacteria

These autotrophic cyanobacteria are the microorganisms fixing carbon for the entire ocean, yet they only make up 8% of the population. These microbes control the amount of organic carbon available in the upper 200m of the ocean, which in turn affects the population of the microbes in this environment.

**What is the difference between an autotroph, heterotroph, and a lithotroph?**  
Autotroph - CO2 is the carbon source (fixes inorganic carbon into biomass)  
Heterotroph - Uses organic carbon as the carbon source (assimilates organic carbon into biomass)  
Lithotroph - Uses inorganic compounds (minerals) as the energy source (electron donor)  

**Based on information provided in the text and your knowledge of geography what is the deepest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this depth?**  
Deepest habitat: 14 km below sea level; 4km deep in the ground, below 10 km of water in the Marianas Trench.  
limiting factor: The temperature 4km deep in the ground is 125 Celcius, above which microorganisms can't survive.  

**Based on information provided in the text your knowledge of geography what is the highest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this height?**  
Highest habitat: Microbes (spores, mainly) can be found as high as 57-77 km up in atmosphere, but 20 km is the highest that typically metabolizing microorganisms are found.  
Limiting factor: Lack of nutrients and cold temperatures prevent microbes from being found above these heights. The maximum height at which spores and dead microbes are found is also controlled by their transfer up into the atmosphere, from wind etc.

**Based on estimates of prokaryotic habitat limitation, what is the vertical distance of the Earth’s biosphere measured in km?**  
The range across which microorganisms are found: 14km below sea level + 77km in the atmosphere = 91 km

The range across which microorganisms metabolize: 14 km below sea level + 20 km to the top of everest = 34 km

**How was annual cellular production of prokaryotes described in Table 7 column four determined? (Provide an example of the calculation)**  
To calculate the annual cellular production of prokaryotes, the total number of cells is multiplied by the number of turnovers each year.

Example calculation for Marine heterotrophs:  
(3.6 x 10^28^ cells) x (365 days/yr) x (1/16 day) = 8.21 x 10^29^ cells/year

**What is the relationship between carbon content, carbon assimilation efficiency and turnover rates in the upper 200m of the ocean? Why does this vary with depth in the ocean and between terrestrial and marine habitats?**  
The amount of carbon available in the ocean (and any habitat) will be one of the factors controlling the turnover rate of microbes; if you don’t have the carbon to make another cell, you won’t be making more cells and therefore the turnover will take longer. Additionally, if the carbon-assimilation efficiency is constant (20%), microorganisms with a higher carbon content will need more carbon to duplicate. 

Carbon content decreases with depth. In both the ocean and terrestrial habitats there is less life as you go deeper in the habitats. Plants are on the surface of terrestrail habitats, and most marine life remains in the first few (hundred) meters of the ocean, due to oxygen and sunlight contraints. If there is less other life, there will be fewer carbon sources as you go deeper into these environments, and thus there will be less available carbon. 

Example calculation using Marine heterotrophs above 200m:       
5-20 fg of C/cell, use average 10 fg C/cell = 10 x 10^-30^ Peta grams/cell x 3.6 x 10^28^ cells=    0.36 Pg C in marine heterotrophs x 4 = 1.44 Pg/yr C used
        where 4 represents the C assimilation efficiency

Roughly 51 Pg C/yr x 85% consumed = 43 Pg C/yr
(43 Pg/yr)/(1.44 Pg/yr C used) = 29.9 turnovers per year  ——> 12.2 days per turnover, close to the 16 day turnover time reported in the paper

**How were the frequency numbers for four simultaneous mutations in shared genes determined for marine heterotrophs and marine autotrophs given an average mutation rate of 4 x 10-7 per DNA replication? (Provide an example of the calculation with units. Hint: cell and generation cancel out)**  
(4 x 10^-7^ mutations/gene/DNA replication)^4^ = 2.56 x 10^-26^ mutations/generation; the power of four comes from having four mutations at once (4 x 10^-7^ = one mutation)

Example calculation for Marine sediments:  
3.6 x 10^28^ cells x (365 days/yr) x (1 turnover/16days) = (8.2 x 10^29^ cells/yr) x (2.56 x 10^-26^ mutations/generation) = 2.1 x 10^4^ mutations/yr = 57.53 mutations/hour

**Given the large population size and high mutation rate of prokaryotic cells, what are the implications with respect to genetic diversity and adaptive potential? Are point mutations the only way in which microbial genomes diversify and adapt?**    
Mutations are one way by which genetic diversiy is created and by which microbes can adapt to new environmental pressures. Not all mutations will result in a successful microorganism, but some will. Mutations have an expected probability of occurring, and using a population size the frequency of mutations ca be determined (as in questions above). Thus, in large populations mutations will occur much more frequently than in small populations, and this is part of what makes mmiicrobes so diverse and easily adaptable. Of course, microbes diversify and adapt via horizontal gene transfer. By sharing genetic information between microbes, "verified" genetic code (genetic code that has been proven to work, unlike mutations) from dissimilar metabolisms and new proteins (etc) can be shared. The microbe may not have an immediate use for the shared genetic code, but given an environmental stress down the line the microbe will be able to express the shard gene to survive.

**What relationships can be inferred between prokaryotic abundance, diversity, and metabolic potential based on the information provided in the text?**    
The more abundant microbes are, the more potential there is for mutation as well as horizontal gene transfer. This leads to genetic diversity, and as microbes diversify they gain (and develop) new matabolic pathways. As more metabolic pathways open to microbes, they will be able to expand into new environmental niches, which leads to microbes being more abundant. It all acts as a cycle, and serves to ensure the continued exsistence of microorganisms.